
replicas: 1
minReplicas: 0

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 200Mi

service:
  port: 8080

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

prometheus:
  enabled: true

serviceAccount:
  enabled: true
  name: namespace-operator-writer-elector-operator